services:
  back:
    build: https://github.com/Katy248/electrotech.git
    restart: unless-stopped
    volumes:
      - data:/data
      - database:/database
    ports:
      - "8021:8021"
      - "30000-30020:30000-30020"
    environment:
      # do not configure
      EL_CATALOG_DATA_DIR: "/data"
      EL_DB_AUTO_MIGRATE: true
      # configuration needs to edit dependencies
      EL_PORT: "${PORT:-8080}"
      EL_DB_CONNECTION_STRING: "${DB_CONNECTION_STRING:-/database/database.sqlite3}"
      # configure via .env
      EL_AUTH_SECRET: "${AUTH_SECRET}"
      EL_FTP_USERNAME: "${FTP_USERNAME}"
      EL_FTP_PASSWORD: "${FTP_PASSWORD}"
      EL_FTP_PUBLIC_IP: "${FTP_PUBLIC_IP}"
      EL_MAIL_HOST: "${MAIL_HOST}"
      EL_MAIL_PORT: "${MAIL_PORT}"
      EL_MAIL_USERNAME: "${MAIL_USERNAME}"
      EL_MAIL_PASSWORD: "${MAIL_PASSWORD}"
      EL_MAIL_INFO_RECEIVER: "${MAIL_INFO_RECEIVER}"
      EL_MAIL_INFO_SENDER: "${MAIL_INFO_SENDER}"


    networks:
      - default

  front:
    build: https://github.com/icentr/electrotech-front.git
    restart: unless-stopped
    depends_on:
      - back
    environment:
      NUXT_PUBLIC_API_BASE: "${API_BASE_URL}"
    networks:
      - default

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - back
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - default

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: "${DATA_DIR}"
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: "${DB_DIR}"
      o: bind

networks:
  default:
    driver: bridge
