services:
  back:
    build: https://github.com/Katy248/electrotech.git
    restart: unless-stopped
    volumes:
      - data:/data
      - database:/database
    ports:
      - "8021:8021"
      - "30000-30020:30000-30020"
    environment:
      EL_PORT: "${PORT:-8080}"
      EL_CATALOG_DATA_DIR: "/data"
      EL_AUTH_SECRET: "${AUTH_SECRET}"
      EL_DB_CONNECTION_STRING: "${DB_CONNECTION_STRING:-/database/database.sqlite3}"
      EL_DB_AUTO_MIGRATE: true

    networks:
      - default

  front:
    build: https://github.com/icentr/electrotech-front.git
    restart: unless-stopped
    depends_on:
      - back
    environment:
      NUXT_PUBLIC_API_BASE: "${API_BASE_URL}"
    networks:
      - default

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - back
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - default

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: "${DATA_DIR}"
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: "${DB_DIR}"
      o: bind

networks:
  default:
    driver: bridge
